version: "3.8"

services:
  web:
    build: .
    container_name: giftcard_app
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=${SECRET_KEY}
      - DJANGO_DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=techXplore_hakathon1.settings
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}
      - EMAIL=${EMAIL}
    depends_on:
      - db



  db:
    image: postgres:latest
    container_name: giftcarddb
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
