# Generated by Django 5.1.6 on 2025-02-21 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_giftcard_cvv_giftcard_exp_month_giftcard_exp_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='gift_type',
            field=models.CharField(choices=[('myself', 'For Myself'), ('single', 'Gift to Someone Else')], default='myself', max_length=10),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_gift_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
